### ISSUE TITLE
unable to find attributes.csv

### ISSUE THREAD

**Issue by don-jacob** [e3-/resolve#15]
Thank you for this package. Going through the documentation I was able to get it to run via command line. Unfortunately I hit an issue while running. 

FileNotFoundError: [Errno 2] No such file or directory: '/home/MY_FOLDER/resolve/data/settings/resolve/Core_25MMT/attributes.csv'

To reproduce:
(resolve-env) hpwsl@HP:/home/MY_FOLDER/resolve/src/resolve/resolve$ python run_opt.py Core_25MMT --solver-name cbc
2000-01-01 00:00:01.973 | INFO       | __main__:main:191 - Resolve version: 0.1.2
2000-01-01 00:00:02.033 | INFO       | __main__:main:206 - Loading Resolve case: Core_25MMT
2000-01-01 00:00:02.186 | ERROR    | __main__:main:241 - Case Core_25MMT failed. See error traceback below:
2000-01-01 00:00:02.213 | ERROR    | __main__:main:242 - Traceback (most recent call last):
  File "/home/MY_FOLDER/resolve/src/resolve/resolve/run_opt.py", line 227, in main
    resolve_model = _run_case(
  File "/home/MY_FOLDER/resolve/src/resolve/resolve/run_opt.py", line 125, in _run_case
    _, resolve_model = model_formulation.ResolveCase.from_csv(
  File "/home/MY_FOLDER/resolve/src/resolve/core/component.py", line 394, in from_csv
    input_df = pd.read_csv(filename).sort_index()
  File "/home/hpwsl/miniconda3/envs/resolve-env/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/hpwsl/miniconda3/envs/resolve-env/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/hpwsl/miniconda3/envs/resolve-env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/hpwsl/miniconda3/envs/resolve-env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/hpwsl/miniconda3/envs/resolve-env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/hpwsl/miniconda3/envs/resolve-env/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/home/hpwsl/miniconda3/envs/resolve-env/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/MY_FOLDER//resolve/data/settings/resolve/Core_25MMT/attributes.csv'

**Comment by dommara2** [comment]
I'm facing the same issue. Please let me know if the issue is resolved.
